### PR TITLE
structure: else, elseif, break (bugfix)

### PR DESCRIPTION
**Pull request by wickedOne**
fixes several bugs in the return or throw sniff

should now raise appropriate errors when tested with for example
```php
<?php

namespace Symfony;

class Ex
{
    public function __construct()
    {
        if ($a === $b) {
            if ($b === $c) {
                return null;
            }
        } else { # this one was a false positive
            $b = $a;
        }
    }

    public function baz($foo, $bar)
    {
        if ($foo === 1) {
            throw new \Exception('Bar'.$foo);
        } else {
            $foo = $bar;
        }
    }

    public function foo()
    {
        switch($a)
        {
            case 1:
                return null;
            case 2:
                $a = $b;
                return null;
                break; # this one was ignored
        }
    }
}
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@wickedOne  I think you have trouble with : 

```
if ('string' === $dummy) {
            if ('values' === $mergedOptions['some_default']) {
                return substr($dummy, 0, 5);
            }

            return ucwords($dummy);
        }

        if ('int' === $dummy) {
            if ('values' === $mergedOptions['some_default']) {
                substr($dummy, 0, 5);
            } elseif (true) {
                return ucwords($dummy);
            }
        }
```

**Comment by wickedOne** [comment]
thanks @VincentLanglet !
i'll try to have a look at it somewhere this week.

**Comment by wickedOne** [comment]
@VincentLanglet i've modified the sniff so it expects the else(if) statement on the same line as scope closer of the if statement.

so that is assuming nobody does something horrible like
```php
// ...
if ($foo === $bar) {
    return null;
}
else {
    $bar = $foo;
}
```

**Comment by djoos** [comment]
Thanks @wickedOne!

**Pull request merged**
